version: 2

jobs:

 build:
   docker:
    - image: docker

   steps:
    - checkout
    - setup_remote_docker

    - run:
       name: install docker
       command:  |
        docker -v && docker-compose -v
        docker-compose -f  deployment/docker-compose-build.yaml build --parallel