version: 2

jobs:

 build:
   docker:
    - image: docker

   steps:
    - checkout

    - run:
       name: install docker
       command:  |
        docker -v && docker-compose -v
        service status docker
        service start docker
   
    - run:
       name: build Udagram-Api-Feed
       command:  
    
        docker build -t newthingade/udagram-api-feed:v1 -f /root/project/udagram-api-feed .


    - run:
       name: build Udagram-Api-User
       command: docker build -t newthingade/udagram-api-user:v2 -f /root/project/udagram-api-user .

    - run:
       name: build Udagram-Frontend
       command: docker build -t newthingade/udagram-frontend:v3 -f /root/project/udagram-frontend .

    - run:
       name: build Udagram-reverseproxy
       command: docker build -t newthingade/udagram-reverseproxy:v4 -f /root/project/udagram-reverseproxy .
    
    
    - run:
       name:  Push build Udagram-Api-Feed
       command: |
         docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
         docker push newthingade/udagram-api-feed:v1
   
   
    - run:
       name:  Push build Udagram-Api-User
       command: |
         docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
         docker push newthingade/udagram-api-user:v2
   
    - run:
       name:  Push build Udagram-Frontend
       command: |
         docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
         docker push newthingade/udagram-frontend:v3
    
    - run:
       name:  Push build Udagram-reverseproxy
       command: |
         docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
         docker push newthingade/udagram-reverseproxy:v4


workflows:
  version: 2
  default:
    jobs:
      - build